global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090', 'kafka_exporter:1337', 'hdfs_directory_exporter:42069']
